### ISSUE TITLE
Dealing with polymorphism

### ISSUE THREAD

**Issue by andronekomimi** [joepickrell/fgwas#10]
Hello,

It seems impossible to use fgwas on polyallelic sites.
I've got the following error message :
ERROR: SNPs out of order
Chromosome 1. Position 10298764 seen before 10298764.
What would be the best way to deal with this without altering fgwas behavior ?

Many thanks
Audrey

**Comment by joepickrell** [comment]
Thanks for the report. Yes, you're correct that this is not currently well-handled. We assume all sites are bi-allelic and use chromosome + position to split the markers into blocks. 

The algorithm will run (and I think give correct results) if you treat each allele as a bi-allelic polymorphism and give them different positions (e.g. 10298764 and 10298765). As long as you give both the exact same annotations, the position is only used to split the genome into blocks, so this should be fine (as long as you don't split the two across two blocks).

**Comment by andronekomimi** [comment]
Thank you for your really quick answer. I'll do so :-)
