### ISSUE TITLE
Annotation enrichments from fgwas - what is the base of the logartihm?

### ISSUE THREAD

**Issue by kauralasoo** [joepickrell/fgwas#13]
Hello,

In the <prefix>.params output file, fgwas reports the enrichment values for each annotation used as well as the 95% confidence intervals. Are these enrichments on the log scale? If yes, what is the base of the logarithm used? Maybe I missed something, but I could not find it in the documentation

Kind regards,
Kaur

**Comment by Jeremy37** [comment]
The enrichments are on the natural log scale, base e.

**Comment by kauralasoo** [comment]
Thanks!
